<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\QueryService.Domain\QueryService.Domain.csproj" />
      <ProjectReference Include="..\QueryService.Infrastructure\QueryService.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Runtime\Workers\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.6" />
    </ItemGroup>

</Project>
