// <auto-generated />
using System;
using Domain.Enums;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace QueryService.Infrastructure.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260908193025_QS2_IndexAndFilters")]
    partial class QS2_IndexAndFilters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "query_state", new[] { "completed", "failed", "not_set", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "query_type", new[] { "not_set", "user_statistics" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Query.EQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор сущности");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_time")
                        .HasComment("Время, когда запрос завершился.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Дата создания");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message")
                        .HasComment("Сообщение от запроса.");

                    b.Property<QueryType>("QueryType")
                        .HasColumnType("query_type")
                        .HasColumnName("query_type")
                        .HasComment("Тип запроса.");

                    b.Property<QueryState>("State")
                        .HasColumnType("query_state")
                        .HasColumnName("query_state")
                        .HasComment("Состояние запроса.");

                    b.HasKey("Id");

                    b.HasIndex("QueryType");

                    b.HasIndex("State");

                    b.ToTable("query", t =>
                        {
                            t.HasComment("Таблица с текущими запросами.");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Query.EQueryUserStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор сущности");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Дата создания");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_from")
                        .HasComment("Фильтр по дате - Дата От.");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_to")
                        .HasComment("Фильтр по дате - Дата По.");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid")
                        .HasColumnName("query_id")
                        .HasComment("Идентификатор запроса.");

                    b.Property<int?>("SignInCount")
                        .HasColumnType("integer")
                        .HasColumnName("sign_in_count")
                        .HasComment("Количество входов.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя.");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("query_user_statistics", t =>
                        {
                            t.HasComment("Данные для запросов по статистике пользователей.");
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.EUserSignIn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор сущности");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Дата создания");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя.");

                    b.HasKey("Id");

                    b.ToTable("user_sign_in", t =>
                        {
                            t.HasComment("Данные по авторизации пользователей.");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Query.EQueryUserStatistics", b =>
                {
                    b.HasOne("Domain.Entities.Query.EQuery", "Query")
                        .WithMany("QueryUserStatistics")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Domain.Entities.Query.EQuery", b =>
                {
                    b.Navigation("QueryUserStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
