// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Domain.Enums;
using Infrastructure;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "query_state", new[] { "completed", "failed", "not_set", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "query_type", new[] { "not_set", "user_statistics" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QueryService.Domain.Entities.Query.EQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор сущности");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Дата создания");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message")
                        .HasComment("Сообщение от запроса.");

                    b.Property<QueryType>("QueryType")
                        .HasColumnType("query_type")
                        .HasColumnName("query_type")
                        .HasComment("Тип запроса.");

                    b.Property<QueryState>("State")
                        .HasColumnType("query_state")
                        .HasColumnName("query_state")
                        .HasComment("Состояние запроса.");

                    b.HasKey("Id");

                    b.ToTable("query", t =>
                        {
                            t.HasComment("Таблица с текущими запросами.");
                        });
                });

            modelBuilder.Entity("QueryService.Domain.Entities.Query.EQueryUserStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор сущности");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Дата создания");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid")
                        .HasColumnName("query_id")
                        .HasComment("Идентификатор запроса.");

                    b.Property<int>("SignInCount")
                        .HasColumnType("integer")
                        .HasColumnName("sign_in_count")
                        .HasComment("Количество входов.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя.");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("query_user_statistics", t =>
                        {
                            t.HasComment("Данные для запросов по статистике пользователей.");
                        });
                });

            modelBuilder.Entity("QueryService.Domain.Entities.User.EUserSignIn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор сущности");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Дата создания");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя.");

                    b.HasKey("Id");

                    b.ToTable("user_sign_in", t =>
                        {
                            t.HasComment("Данные по авторизации пользователей.");
                        });
                });

            modelBuilder.Entity("QueryService.Domain.Entities.Query.EQueryUserStatistics", b =>
                {
                    b.HasOne("QueryService.Domain.Entities.Query.EQuery", "Query")
                        .WithMany("QueryUserStatistics")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("QueryService.Domain.Entities.Query.EQuery", b =>
                {
                    b.Navigation("QueryUserStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
